[package]
name = "som"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]

[[bin]]
name = "som-parser"
test = false

[[bin]]
name = "som-tokenizer"
test = false

[lib]
name = "som"
doc = false
doctest = false
